### ISSUE TITLE
Proxy is not being hit when we use kolibri node.

### ISSUE THREAD

**Issue by balamuruganvasudevan** [hms-networks/node-red-contrib-kolibri#3]
Hi,
I am fetching the data from cloud using Kolibri Node (node-red-contrib-kolibri). This node works fine in internet, when i move the system into intranet (behind corporate proxy), its throwing an error.  i could manually open the portal through chrome/Internet Explorer from the same machine.
Based on googling, i had set http_proxy environment variable and tried, but failed.
Any support on handling proxy with node-red would be much helpful.

**Comment by arbue** [comment]
Hi,
currently there is no support to specify proxy settings on the node. I will look into this.

**Comment by arbue** [comment]
Hi @balamuruganvasudevan,

Could you please test the initial proxy support (PR #4)  in your environment and provide feedback if this solves your issue?

**Comment by balamuruganvasudevan** [comment]
@arbue Thank you so much for your support. 
Yes, its working fine as expected.  Have tested and confirmed.

**Comment by arbue** [comment]
The PR #4 will be included in the next few days in the next release. Thanks!
