### ISSUE TITLE
Request value by specified time interval

### ISSUE THREAD

**Issue by kihana** [hms-networks/node-red-contrib-kolibri#9]
Hello,

Is it possible to get value by the specified time interval in kolibri in node?

**Comment by arbue** [comment]
Hello, 
I think you are referring to the kolibri.node.getHistory RPC call, where you can specify a time range to retrieve historical data values.   
The current version of the node red plugin does not support that call. The plugin supports only a small subset of kolibri protocol RPCs mainly for retrieving / writing live data values via the kolibri.subscribe / kolibri.write RPC calls.
